name: thozha
description: A personal safety app integrated with smartwatches.

# Add your SDK constraint here
environment:
  sdk: '>=3.4.0 <4.0.0' # Specifies the range of Dart SDK versions the project is compatible with

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  provider: ^6.0.5
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^6.2.1
  speech_to_text: ^6.6.0
  firebase_messaging: 15.1.0
  firebase_messaging_web: 3.8.13
  web: 0.5.1
  permission_handler: 11.3.1
  shared_preferences: 2.3.2
  url_launcher: 6.3.0
  location: ^7.0.0
  geolocator: ^12.0.0


# Add any other dependencies you need for your project here

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  html: ^0.15.0

# Your assets and fonts configuration goes here
flutter:
  assets:
    - assets/google_logo.png
    - assets/background-img.png